name: Wiki Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Install and Build
      run: |
        # git
        git config --global user.name "huxins"
        git config --global user.email "huxins@163.com"
        # vuepress
        yarn global add vuepress
        # build
        npm install
        npm run docs:build
        # git push
        cd docs/.vuepress/dist
        git init
        git add -A
        git commit -m "first commit"
        git push -f ${{ secrets.git }} master:gh-pages
